{
  "swagger": "2.0",
  "info": {
    "description": "This is a Kenzie Courses API",
    "version": "1.0.0",
    "title": "Simple Inventory API",
    "contact": {
      "email": "rbsndev3@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "tags": [
    {
      "name": "users",
      "description": "Users routes"
    },
    {
      "name": "courses",
      "description": "Courses routes"
    }
  ],
  "paths": {
    "/login": {
      "post": {
        "tags": ["users"],
        "summary": "user login",
        "operationId": "userLogin",
        "description": "Login route, returns user access token if credentials are correct.",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "in": "body",
            "name": "LoginUser",
            "description": "User credentials.",
            "schema": {
              "type": "object",
              "required": ["email", "password"],
              "properties": {
                "email": {
                  "type": "string",
                  "example": "jhondoe@mail.com"
                },
                "password": {
                  "type": "string",
                  "example": "kytr235fv"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "example": {
                "token": "fhjhfjshfhl767gg76aa-ajiarigj"
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "type": "object",
              "example": {
                "message": "Invalid credentials"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "example": {
                "message": ["password is a required field"]
              }
            }
          }
        }
      }
    },
    "/users": {
      "post": {
        "tags": ["users"],
        "summary": "create user",
        "operationId": "creaetUser",
        "description": "Route to create a new user",
        "produces": ["application/json"],
        "parameters": [
          {
            "in": "body",
            "name": "CreateUser",
            "description": "Create new user",
            "schema": {
              "type": "object",
              "required": ["firstName", "lastName", "email", "password"],
              "properties": {
                "firstName": {
                  "type": "string",
                  "example": "Jhon"
                },
                "lastName": {
                  "type": "string",
                  "example": "Doe"
                },
                "email": {
                  "type": "string",
                  "example": "jhondoe@mail.com"
                },
                "password": {
                  "type": "string",
                  "example": "kytr235fv"
                },
                "isAdm": {
                  "type": "boolean",
                  "example": true
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "type": "object",
              "example": {
                "id": "d290f1ee-6c54-4b01-90e6-d701748f0851",
                "firstName": "jhon",
                "lastName": "Doe",
                "email": "jhondoe@mail.com",
                "password": "kytr235fv",
                "isAdm": true,
                "createdAt": "2022-06-05 15:44:40.290",
                "updatedAt": "2022-06-05 15:44:40.290"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "example": {
                "message": ["password is a required field"]
              }
            }
          },
          "409": {
            "description": "Conflict",
            "schema": {
              "type": "object",
              "example": {
                "message": "Email already exists"
              }
            }
          }
        }
      },
      "get": {
        "tags": ["users"],
        "summary": "get all users",
        "operationId": "GetUsers",
        "description": "This route is to get all users. Only admin users have access.",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/User"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "example": {
                "message": "Missing authorization token."
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "type": "object",
              "example": {
                "message": "You are not allowed to access this information"
              }
            }
          }
        }
      }
    },
    "/users/:id": {
      "get": {
        "tags": ["users"],
        "summary": "get user by id",
        "operationId": "GetUserById",
        "description": "This route is to get the user by ID. Only admin users have access.",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "object",
              "example": {
                "id": "d290f1ee-6c54-4b01-90e6-d701748f0851",
                "firstName": "jhon",
                "lastName": "Doe",
                "email": "jhondoe@mail.com",
                "password": "kytr235fv",
                "isAdm": true,
                "createdAt": "2022-06-05 15:44:40.290",
                "updatedAt": "2022-06-05 15:44:40.290"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "example": {
                "message": "Missing authorization token."
              }
            }
          },
          "403": {
            "description": "Forbiden",
            "schema": {
              "type": "object",
              "example": {
                "message": "You can't access information of another user"
              }
            }
          }
        }
      },
      "patch": {
        "tags": ["users"],
        "summary": "update user by id",
        "operationId": "UpdateUserById",
        "description": "This route is to update user by ID. Only admin users have access.",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "in": "body",
            "name": "Update user",
            "description": "update one user",
            "schema": {
              "type": "object",
              "properties": {
                "firstName": {
                  "type": "string",
                  "example": "Jhon"
                },
                "lastName": {
                  "type": "string",
                  "example": "Doe"
                },
                "email": {
                  "type": "string",
                  "example": "jhondoe2@mail.com"
                },
                "password": {
                  "type": "string",
                  "example": "jkhghdhejnfs"
                },
                "isAdm": {
                  "type": "boolean",
                  "example": false
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "object",
              "example": {
                "id": "d290f1ee-6c54-4b01-90e6-d701748f0851",
                "firstName": "Jhon",
                "lastName": "Doe",
                "email": "jhondoe2@mail.com",
                "password": "jkhghdhejnfs",
                "isAdm": false,
                "createdAt": "2022-06-05 15:44:40.290",
                "updatedAt": "2022-06-05 15:50:10.110"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "example": {
                "message": "Missing authorization token."
              }
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "type": "object",
              "example": {
                "message": "User not found"
              }
            }
          },
          "409": {
            "description": "Conflict",
            "schema": {
              "type": "object",
              "example": {
                "message": "User already exists"
              }
            }
          }
        }
      }
    },
    "/courses": {
      "post": {
        "tags": ["courses"],
        "summary": "Create Course",
        "operationId": "CreateCourse",
        "description": "",
        "produces": ["application/json"],
        "parameters": [
          {
            "in": "body",
            "name": "inventoryItem",
            "description": "Inventory item to add",
            "schema": {
              "type": "object",
              "required": ["courseName", "duration"],
              "properties": {
                "courseName": {
                  "type": "string",
                  "example": "PHP"
                },
                "duration": {
                  "type": "string",
                  "example": "6 mounths"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "type": "object",
              "example": {
                "id": "1e810d53-bc38-4707-9492-5a45a1e3ea89",
                "courseName": "PHP",
                "duration": "6 mounth"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "example": {
                "message": ["duration is a required field"]
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "type": "object",
              "example": {
                "message": "You are not allowed to access this information"
              }
            }
          },
          "409": {
            "description": "Conflict",
            "schema": {
              "type": "object",
              "example": {
                "message": "Course already exists"
              }
            }
          }
        }
      },
      "get": {
        "tags": ["courses"],
        "summary": "Get all courses",
        "operationId": "GetAllCourses",
        "description": "This route is for get all courses",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "responses": {
          "201": {
            "description": "GetAllCourses",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Course"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "example": {
                "message": "Missing authorization token."
              }
            }
          }
        }
      }
    },
    "/courses/:id": {
      "patch": {
        "tags": ["courses"],
        "summary": "Update course by ID",
        "operationId": "UpdateCourse",
        "description": "Route to update a course",
        "produces": ["application/json"],
        "parameters": [
          {
            "in": "body",
            "name": "updateCourse",
            "description": "update a course",
            "schema": {
              "type": "object",
              "required": ["courseName", "duration"],
              "properties": {
                "courseName": {
                  "type": "string",
                  "example": "PHP"
                },
                "duration": {
                  "type": "string",
                  "example": "6 mounths"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "object",
              "example": {
                "id": "1e810d53-bc38-4707-9492-5a45a1e3ea89",
                "courseName": "Java",
                "duration": "6 mounth"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "example": {
                "message": "Missing authorization token."
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "type": "object",
              "example": {
                "message": "You are not allowed to access this information"
              }
            }
          },
          "404": {
            "description": "Not Foun",
            "schema": {
              "type": "object",
              "example": {
                "message": "course with id 4c25bb53-fa99-42a0-98f6-9360c4c6d141 no found"
              }
            }
          },
          "409": {
            "description": "Conflict",
            "schema": {
              "type": "object",
              "example": {
                "message": "Course already exists"
              }
            }
          }
        }
      }
    },
    "/courses/:id/users": {
      "post": {
        "tags": ["courses"],
        "summary": "register student",
        "operationId": "RegisterNewStudend",
        "description": "Route to enroll a new student in the course",
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "example": {
                "message": "Enrollment email sent successfully."
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "example": {
                "message": "Missing authorization token."
              }
            }
          },
          "404": {
            "description": "Not Foun",
            "schema": {
              "type": "object",
              "example": {
                "message": "course with id 4c25bb53-fa99-42a0-98f6-9360c4c6d141 no found"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "User": {
      "type": "object",
      "required": ["firstName", "lastName", "email", "password"],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid",
          "example": "d290f1ee-6c54-4b01-90e6-d701748f0851"
        },
        "firstName": {
          "type": "string",
          "example": "Jhon"
        },
        "lastName": {
          "type": "string",
          "example": "Doe"
        },
        "email": {
          "type": "string",
          "format": "email",
          "example": "jhondoe@mail.com"
        },
        "password": {
          "type": "string",
          "example": "kytr235fv"
        },
        "isAdm": {
          "type": "boolean",
          "example": true
        },
        "createdAt": {
          "type": "string",
          "format": "date-time",
          "example": "2022-06-05 15:44:40.290"
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time",
          "example": "2022-06-05 15:44:40.290"
        }
      }
    },
    "UserRelationship": {
      "type": "object",
      "required": ["firstName", "lastName", "email", "password"],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid",
          "example": "d290f1ee-6c54-4b01-90e6-d701748f0851"
        },
        "firstName": {
          "type": "string",
          "example": "Jhon"
        },
        "lastName": {
          "type": "string",
          "example": "Doe"
        },
        "email": {
          "type": "string",
          "format": "email",
          "example": "jhondoe@mail.com"
        },
        "password": {
          "type": "string",
          "example": "kytr235fv"
        },
        "isAdm": {
          "type": "boolean",
          "example": true
        },
        "createdAt": {
          "type": "string",
          "format": "date-time",
          "example": "2022-06-05 15:44:40.290"
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time",
          "example": "2022-06-05 15:44:40.290"
        },
        "courses": {
          "$ref": "#/definitions/Course"
        }
      }
    },
    "Course": {
      "type": "object",
      "required": ["courseName", "duration"],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid",
          "example": "fd8be6fc-e77d-47ab-bfe6-59daea4439da"
        },
        "courseName": {
          "type": "string",
          "example": "PHP"
        },
        "duration": {
          "type": "string",
          "example": "6 mounths"
        }
      }
    },
    "CourseRelationship": {
      "type": "object",
      "required": ["courseName", "duration"],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid",
          "example": "fd8be6fc-e77d-47ab-bfe6-59daea4439da"
        },
        "courseName": {
          "type": "string",
          "example": "PHP"
        },
        "duration": {
          "type": "string",
          "example": "6 mounths"
        },
        "students": {
          "$ref": "#/definitions/User"
        }
      }
    }
  },
  "host": "localhost",
  "basePath": ":3000",
  "schemes": ["http"]
}
